"""Run a SearXNG instance for the user (optional).

SearXNG is a separate service — it can't be imported into this process — but
the app can still own its lifecycle so "use SearXNG" is a button rather than a
setup guide. We generate a settings file that enables the JSON API (the one
step people always miss), start it, wait for it to answer, and hand back the
URL.

There are two ways to run it, and Docker is only the tidier one:

- **docker** — pull the official image and run a container. Preferred when
  Docker is installed, because upgrades and isolation come for free.
- **source** — SearXNG is a Python app, so it also runs in a virtualenv of its
  own under the data directory, started as a child process. Slower to set up
  (a pip install from git) and it needs `git`, but it needs no Docker at all.

Everything degrades: no backend available, or a failed start, returns a plain
reason and leaves web search on DuckDuckGo.
"""

from __future__ import annotations

import ctypes
import json
import logging
import os
import secrets
import shutil
import signal
import socket
import stat
import subprocess
import sys
import threading
import time
from pathlib import Path

from memorymap.search import websearch

CONTAINER_NAME = "memorymap-searxng"
IMAGE = "searxng/searxng:latest"
HOST_PORT = 8888
BASE_URL = f"http://localhost:{HOST_PORT}"
START_TIMEOUT = 90  # image pulls can be slow the first time
COMMAND_TIMEOUT = 20

# The source, as an archive we download and unpack ourselves.
#
# Not a `git clone`, and not `pip install <tarball-url>` either, because
# **SearXNG's repository cannot be written to a Windows filesystem**. Four of
# its files carry a colon in the name:
#
#     utils/templates/etc/nginx/default.apps-available/searxng.conf:socket
#     utils/templates/etc/httpd/sites-available/searxng.conf:socket
#     utils/templates/etc/uwsgi/apps-available/searxng.ini:socket
#     utils/templates/etc/uwsgi/apps-archlinux/searxng.ini:socket
#
# A colon separates a drive letter (and names an alternate data stream), so
# Windows refuses those names outright. git fetches every object happily and
# then dies at the last step — *"error: invalid path …searxng.conf:socket /
# fatal: unable to checkout working tree"*, which is what the user reported —
# leaving a half-written checkout behind, which is where the earlier "does
# not appear to be a Python project" came from. Retrying could never work:
# nothing about it is transient. Unpacking the tarball with pip fails the same
# way for the same reason, so "install without git" was equally broken there.
#
# We therefore unpack it ourselves and skip the handful of members Windows
# can't represent. They are nginx and uwsgi deployment templates for
# installing SearXNG on a server — nothing the app runs.
SOURCE_TARBALL = "https://github.com/searxng/searxng/archive/refs/heads/master.tar.gz"
DOWNLOAD_TIMEOUT = 300
INSTALL_TIMEOUT = 900  # a cold pip install builds a few wheels

# use_default_settings keeps SearXNG's own defaults and layers ours on top —
# the important bit being the json format, without which the API returns 403.
SETTINGS_TEMPLATE = """# Generated by MemoryMap. Edit freely; it is not overwritten once created.
use_default_settings: true
server:
  secret_key: "{secret}"
  limiter: false
  image_proxy: true
search:
  safe_search: 0
  formats:
    - html
    - json
plugins:
  # Off deliberately. This plugin downloads a rules file from
  # rules1.clearurls.xyz *during startup*, and a failure there is not caught:
  # the fetch raises, `searx.plugins.initialize` propagates it, and the
  # process exits before it ever binds the port. Any machine that is offline,
  # behind a proxy, or merely slow gets "SearXNG started but never answered".
  # MemoryMap strips tracking parameters from result URLs itself
  # (`websearch.strip_tracking`), so nothing is lost by leaving it off.
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: false
"""


class SearxngError(RuntimeError):
    """Something stopped us managing the instance."""


# `docker info` against a stopped daemon is quick to fail, but give it room on
# a cold Docker Desktop rather than calling a slow start "not running".
DAEMON_PROBE_TIMEOUT = 8


def docker_installed() -> bool:
    """Is the docker command on PATH? Says nothing about the daemon."""
    return shutil.which("docker") is not None


def docker_available() -> bool:
    """Can we actually run a container right now?

    Checking only that the binary exists was wrong, and produced exactly the
    failure it should have prevented: with Docker Desktop installed but not
    started, the app picked the Docker backend, tried to create a container,
    and reported "failed to connect to the docker API at npipe:..." — while
    the from-source backend that would have worked was never considered.

    `docker info` is the cheapest question that means "is the daemon up".
    """
    if not docker_installed():
        return False
    try:
        result = subprocess.run(  # noqa: S603 — fixed args, no shell
            ["docker", "info", "--format", "{{.ServerVersion}}"],
            capture_output=True,
            text=True,
            timeout=DAEMON_PROBE_TIMEOUT,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return result.returncode == 0


def source_available() -> bool:
    """True if we could build a virtualenv and fetch SearXNG into it.

    Always true. It used to require the `git` binary, which meant a machine
    with neither Docker nor git could not install SearXNG at all — "I can't
    download searxng", with the UI offering a button that could never work.
    The only real requirements are Python (we are running on it) and a network
    connection, which any install needs anyway. git is not used at all now;
    see SOURCE_TARBALL for why cloning cannot work on Windows.

    Deliberately not a `pip install searxng` from PyPI: SearXNG does not
    publish itself there, so that name is somebody else's package, and
    installing it would be running an unknown author's code because the name
    looked right.
    """
    return True


def preferred_backend() -> str | None:
    """Which way we'd run it: docker if present, else from source."""
    if docker_available():
        return "docker"
    if source_available():
        return "source"
    return None


# --- running from source ------------------------------------------------------

# Progress for the one install that can be running at a time. The install is
# minutes long, so it happens on a worker thread and the settings screen polls
# status() rather than holding a request open.
_install_lock = threading.Lock()

# Reported: "the searxng reinstall doesn't have a progress bar so idk if it
# has frozen or is working". A step name that sits unchanged for four minutes
# while pip builds lxml is indistinguishable from a hang, and the install is
# the longest thing this app does.
#
# So the state carries three things a step name cannot: which numbered stage
# of the install we are in (a bar that moves), a fraction inside the stage
# where one is knowable (the download has a content-length; the unpack has a
# member count), and the last few lines the tools themselves printed — which
# is the only real evidence that something is still happening.
INSTALL_STAGES = 5
_LOG_LINES = 12
_install_state: dict = {
    "running": False,
    "step": "",
    "error": "",
    "stage": 0,
    "stages": INSTALL_STAGES,
    "progress": None,  # 0..1 within the whole install, or None if unknowable
    "log": [],
}


def _install_log(line: str) -> None:
    """Keep the last few lines of what the install is actually doing."""
    text = str(line).strip()
    if not text:
        return
    lines = _install_state["log"]
    lines.append(text)
    del lines[:-_LOG_LINES]


def _install_stage(stage: int, step: str) -> None:
    """Move to a numbered stage. Progress is the stage boundary until
    something inside the stage knows better."""
    _install_state.update(
        {"stage": stage, "step": step, "progress": (stage - 1) / INSTALL_STAGES}
    )
    _install_log(f"— {step}")


def _install_progress(stage: int, fraction: float) -> None:
    """Progress *within* a stage, mapped onto the whole install."""
    fraction = max(0.0, min(1.0, fraction))
    _install_state["progress"] = (stage - 1 + fraction) / INSTALL_STAGES


def _source_dir(data_dir: Path) -> Path:
    return Path(data_dir) / "searxng" / "src"


def _venv_dir(data_dir: Path) -> Path:
    return Path(data_dir) / "searxng" / "venv"


def _venv_python(data_dir: Path) -> Path:
    venv = _venv_dir(data_dir)
    return venv / ("Scripts/python.exe" if os.name == "nt" else "bin/python")


def _pid_file(data_dir: Path) -> Path:
    return Path(data_dir) / "searxng" / "run.json"


def is_checkout(path: Path) -> bool:
    """Does this directory hold a Python project pip could install?

    A directory being *there* was the test, and it is not the same question.
    Reported: "Couldn't install SearXNG: ERROR: file:///…/data/searxng/src does
    not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml'
    found." — a leftover `src` that no longer contained a checkout, handed
    straight to `pip install -e` because it existed.
    """
    path = Path(path)
    return (path / "setup.py").exists() or (path / "pyproject.toml").exists()


# `import searx` costs a Python interpreter start, and the settings screen
# polls status() every few seconds. Once it has succeeded it stays true until
# something removes the install, so only the affirmative answer is kept.
_import_ok: set[str] = set()


def source_installed(data_dir: Path) -> bool:
    """Is SearXNG present in its own virtualenv?

    The checkout directory only exists on the git path — a tarball install
    puts `searx` straight into the venv's site-packages and never creates
    one. So the question that actually matters is whether the venv can
    import `searx`, not whether a source folder is sitting there.

    And a folder that is there but empty is *worse* than one that is missing:
    it used to answer "installed" for both this question and the one
    `install_source` asks, so the app tried to start something that was never
    built and reinstalling skipped the download.
    """
    python = _venv_python(data_dir)
    if not python.exists():
        return False
    if str(Path(data_dir)) in _import_ok:
        return True
    if is_checkout(_source_dir(data_dir)):
        return True
    result = _run([str(python), "-c", "import searx"], timeout=COMMAND_TIMEOUT)
    if result.returncode == 0:
        _import_ok.add(str(Path(data_dir)))
        return True
    return False


def _read_pid(data_dir: Path) -> int | None:
    try:
        record = json.loads(_pid_file(data_dir).read_text(encoding="utf-8"))
        return int(record.get("pid")) or None
    except (OSError, ValueError, TypeError):
        return None


_STILL_ACTIVE = 259
_PROCESS_QUERY_LIMITED_INFORMATION = 0x1000


def _alive_windows(pid: int) -> bool:
    """Ask Windows whether the process is still running, without signalling it.

    `os.kill(pid, 0)` is the POSIX idiom and it is actively destructive here:
    on Windows any signal that isn't CTRL_C_EVENT or CTRL_BREAK_EVENT is
    handed to `TerminateProcess`, so "is it alive?" *killed the instance*,
    with exit code 0, and then answered yes. The settings screen polls
    status(), status() asks `_source_state`, and `_source_state` asked this —
    so a SearXNG that had just started was shot within a couple of seconds of
    starting, every time, and the app then reported that it "started but never
    answered". That is the §8b symptom.
    """
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    handle = kernel32.OpenProcess(_PROCESS_QUERY_LIMITED_INFORMATION, False, pid)
    if not handle:
        # Access denied means something is there; anything else means it isn't.
        return ctypes.get_last_error() == 5  # ERROR_ACCESS_DENIED
    try:
        code = ctypes.c_ulong()
        if not kernel32.GetExitCodeProcess(handle, ctypes.byref(code)):
            return False
        # A process that genuinely exited with 259 reads as alive. That is the
        # documented cost of this check and it beats terminating the process.
        return code.value == _STILL_ACTIVE
    finally:
        kernel32.CloseHandle(handle)


def _alive(pid: int) -> bool:
    """Is this PID still around, without disturbing it?"""
    if os.name == "nt":
        try:
            return _alive_windows(pid)
        except (OSError, AttributeError, ValueError):
            return False
    try:
        os.kill(pid, 0)  # POSIX only: signal 0 checks, it does not deliver
    except OSError:
        return False
    return True


def _terminate(pid: int) -> None:
    """End the process. Raises OSError if it can't be reached."""
    # On Windows os.kill hands the signal number to TerminateProcess, which is
    # what we want *here* — abrupt, but SearXNG has nothing to flush.
    os.kill(pid, signal.SIGTERM)


def _source_state(data_dir: Path) -> str:
    """'running', 'stopped', or 'absent' for the from-source instance."""
    if not source_installed(data_dir):
        return "absent"
    pid = _read_pid(data_dir)
    return "running" if pid and _alive(pid) else "stopped"


# Characters Windows will not accept in a filename, plus the control range.
# Filtered on every platform, not only Windows: an install should contain the
# same files everywhere, and a path we would refuse on one OS is not one to
# rely on from another.
_UNSAFE_CHARS = set('<>:"|?*') | {chr(c) for c in range(32)}


def _unsafe_member(name: str) -> bool:
    """Is this archive member one we refuse to write?

    Two separate concerns, both fatal in their own way:
    - **path traversal** — an absolute path or a `..` hop writes outside the
      directory we were asked to fill;
    - **names Windows cannot represent** — see SOURCE_TARBALL. Skipping these
      is what makes the install possible there at all.
    """
    if name.startswith("/") or name.startswith("\\") or ":" in name.split("/")[0]:
        return True
    parts = name.split("/")
    if any(part == ".." for part in parts):
        return True
    return any(char in _UNSAFE_CHARS for part in parts for char in part)


def _download(url: str, destination: Path, on_progress=None) -> None:
    """Fetch the archive to disk. Streamed — it is tens of megabytes.

    `on_progress(done_bytes, total_bytes)` is called as it goes. GitHub sends
    a content-length here, so this is the one stage of the install with a
    genuinely knowable percentage.
    """
    import requests  # local: the module is importable without a network stack

    try:
        with requests.get(url, stream=True, timeout=DOWNLOAD_TIMEOUT) as response:
            response.raise_for_status()
            total = int(response.headers.get("Content-Length") or 0)
            done = 0
            with destination.open("wb") as handle:
                for chunk in response.iter_content(chunk_size=1 << 16):
                    handle.write(chunk)
                    done += len(chunk)
                    if on_progress:
                        on_progress(done, total)
    except requests.RequestException as exc:
        raise SearxngError(f"Couldn't download SearXNG: {exc}") from exc


def _unpack(archive: Path, into: Path) -> list[str]:
    """Unpack the archive into `into`, dropping its single top-level folder.

    Returns the names that were skipped, so the install can say so rather than
    quietly shipping a different set of files than the archive held.
    """
    import tarfile

    skipped: list[str] = []
    into.mkdir(parents=True, exist_ok=True)
    try:
        with tarfile.open(archive, "r:gz") as tar:
            members = []
            for member in tar.getmembers():
                # A GitHub archive wraps everything in "searxng-master/".
                relative = member.name.split("/", 1)[1] if "/" in member.name else ""
                if not relative:
                    continue
                if not (member.isfile() or member.isdir()) or _unsafe_member(relative):
                    skipped.append(relative)
                    continue
                member.name = relative
                members.append(member)
            # filter="data" refuses absolute paths, links and device nodes in
            # 3.12+; the check above is what covers 3.11 and Windows names.
            if sys.version_info >= (3, 12):
                tar.extractall(into, members=members, filter="data")
            else:  # pragma: no cover - 3.11 only
                tar.extractall(into, members=members)  # noqa: S202 — members vetted above
    except (tarfile.TarError, OSError) as exc:
        raise SearxngError(f"Couldn't unpack SearXNG: {exc}") from exc
    return skipped


def _fetch_source(src: Path, state: dict) -> None:
    """Download and unpack SearXNG into `src`, replacing whatever was there."""
    problem = _remove_tree(src)
    if problem:
        raise SearxngError(f"Couldn't clear the old copy of SearXNG: {problem}")
    archive = src.parent / "searxng-source.tar.gz"
    try:
        _install_stage(2, "Downloading SearXNG…")

        def downloaded(done: int, total: int) -> None:
            if total:
                _install_progress(2, done / total)
            _install_state["step"] = (
                f"Downloading SearXNG… {done // 1_000_000} MB"
                + (f" of {total // 1_000_000} MB" if total else "")
            )

        _download(SOURCE_TARBALL, archive, on_progress=downloaded)
        _install_stage(3, "Unpacking SearXNG…")
        skipped = _unpack(archive, src)
        _install_log(f"Unpacked into {src.name}")
        if skipped:
            _install_log(f"Skipped {len(skipped)} file(s) this filesystem can't hold")
            logging.getLogger("memorymap.searxng").info(
                "Skipped %d file(s) this filesystem can't hold: %s",
                len(skipped),
                ", ".join(skipped[:4]),
            )
    finally:
        archive.unlink(missing_ok=True)
    if not is_checkout(src):
        raise SearxngError(
            "SearXNG downloaded, but no setup.py or pyproject.toml turned up "
            f"in {src}. Try again, or reinstall."
        )


def _install_steps(python: str, src: Path) -> list[tuple[str, list[str]]]:
    """The pip commands that install SearXNG, in the order they must run.

    `pip install -e .` on its own **cannot work**, and never could: SearXNG's
    `setup.py` imports `searx` to read its version, `searx/__init__.py`
    imports `msgspec`, and pip builds in an isolated environment where no
    runtime dependency exists yet. It fails with `ModuleNotFoundError: No
    module named 'msgspec'` before it can declare anything — reproduced here,
    not deduced.

    So the requirements go in first and the package is then built against the
    virtualenv rather than an isolated one. This is what SearXNG's own
    `manage` script does (`pip install --use-pep517 --no-build-isolation
    -e .`), and following it is the whole reason it works.
    """
    return [
        (
            4,
            "Installing dependencies (the long one — a few minutes)…",
            [python, "-m", "pip", "install", "-U", "pip", "setuptools", "wheel"],
        ),
        (
            4,
            "Installing dependencies (the long one — a few minutes)…",
            [python, "-m", "pip", "install", "-r", str(src / "requirements.txt")],
        ),
        (
            5,
            "Installing SearXNG itself…",
            [
                python, "-m", "pip", "install",
                "--use-pep517", "--no-build-isolation", "-e", str(src),
            ],
        ),
    ]


def install_source(data_dir: Path) -> None:
    """Fetch SearXNG into a virtualenv of its own. Minutes, not seconds."""
    with _install_lock:
        if _install_state["running"]:
            raise SearxngError("An install is already running.")
        _install_state.update(
            {"running": True, "step": "", "error": "", "log": [], "progress": 0.0}
        )
    _install_stage(1, "Creating a virtualenv…")

    def work() -> None:
        try:
            src = _source_dir(data_dir)
            src.parent.mkdir(parents=True, exist_ok=True)
            _import_ok.discard(str(Path(data_dir)))
            venv = _venv_dir(data_dir)
            if not _venv_python(data_dir).exists():
                _run([sys.executable, "-m", "venv", str(venv)], timeout=180)
                _install_log(f"Virtualenv created at {venv}")
                if not _venv_python(data_dir).exists():
                    raise SearxngError(
                        "Couldn't create a virtualenv for SearXNG at "
                        f"{venv} — check there is space and that the folder "
                        "is writable."
                    )
            # One path for everyone, git or no git: fetch the archive and
            # unpack it ourselves. Both of the old paths — `git clone` and
            # `pip install <tarball-url>` — write every file in the archive,
            # and four of them cannot exist on Windows.
            _fetch_source(src, _install_state)
            python = str(_venv_python(data_dir))
            for stage, step, args in _install_steps(python, src):
                _install_stage(stage, step)
                # Streamed, not captured: pip prints steadily for minutes here,
                # and those lines are the only evidence the install is alive.
                result = _run_streaming(args, INSTALL_TIMEOUT, _install_log)
                if result.returncode != 0:
                    raise SearxngError(_reason(result, "Couldn't install SearXNG"))
            # pip exiting 0 is not the same as `searx` being importable — a
            # half-installed venv otherwise reads as installed and dies at
            # start, which is the state the reinstall button exists to escape.
            _install_state["step"] = "Checking the install…"
            _install_state["progress"] = 0.98
            check = _run(
                [str(_venv_python(data_dir)), "-c", "import searx"], timeout=COMMAND_TIMEOUT
            )
            if check.returncode != 0:
                raise SearxngError(
                    _reason(check, "SearXNG installed but can't be imported")
                )
            _import_ok.add(str(Path(data_dir)))
            _install_log("SearXNG installed and importable.")
            _install_state.update({"step": "", "progress": 1.0, "stage": INSTALL_STAGES})
        except SearxngError as exc:
            _install_state["error"] = str(exc)
            _install_log(f"Failed: {exc}")
        except Exception as exc:  # noqa: BLE001 — a worker thread must not die silently
            _install_state["error"] = f"Install failed: {exc}"
            _install_log(f"Failed: {exc}")
        finally:
            _install_state["running"] = False

    threading.Thread(target=work, name="searxng-install", daemon=True).start()


def port_report() -> dict:
    """Who, if anyone, is holding the port SearXNG wants.

    "Check the port isn't in use" is advice that assumes the person can check.
    This checks: it binds the port, and if it can't, asks whatever is there
    whether it speaks SearXNG. Those are three genuinely different situations
    — free, occupied by a working SearXNG, occupied by something else — and
    only the last one is a problem the user has to go and solve.
    """
    free = True
    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        # No SO_REUSEADDR: the question is whether a *live* listener holds the
        # port, and reuse would let this bind alongside one on some platforms.
        probe.bind(("127.0.0.1", HOST_PORT))
        probe.close()
    except OSError:
        free = False

    if free:
        return {
            "port": HOST_PORT,
            "free": True,
            "held_by_searxng": False,
            "detail": f"Port {HOST_PORT} is free.",
        }

    answering = websearch.probe_searxng(BASE_URL)
    return {
        "port": HOST_PORT,
        "free": False,
        "held_by_searxng": answering,
        "detail": (
            f"A working SearXNG is already answering on port {HOST_PORT} — "
            "MemoryMap can use it as it is."
            if answering
            else f"Something is using port {HOST_PORT}, and it isn't answering "
            "as SearXNG. Close whatever has it (or stop and reinstall here to "
            "clear a half-dead instance of our own) and try again."
        ),
    }


def _drop_readonly(func, path, _exc) -> None:
    """rmtree's retry hook: clear the read-only bit and go again.

    git marks everything under `.git/objects` read-only, and Windows refuses
    to delete a read-only file however the permissions read elsewhere. With
    `ignore_errors=True` that silently produced the half-deleted tree behind
    the reported error — the loose files went, `.git` stayed, and `src` was
    still *there* with nothing installable in it.
    """
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except OSError:
        pass  # reported by the caller, which checks whether the path survived


def _remove_tree(path: Path) -> str:
    """Delete a directory. Returns "" on success, else why it is still around.

    A tree we cannot delete is moved aside instead. Being unable to remove an
    old install is not a reason to be unable to make a new one, and "go and
    delete this folder by hand" is the advice this whole module exists to
    stop giving.
    """
    path = Path(path)
    if not path.exists():
        return ""
    if not path.is_dir():
        try:
            path.unlink()
        except OSError as exc:
            return f"{path} is a file and couldn't be removed ({exc})"
        return ""
    # onexc replaced onerror in 3.12; both call the same hook here.
    if sys.version_info >= (3, 12):
        shutil.rmtree(path, onexc=_drop_readonly)
    else:  # pragma: no cover - 3.11 only
        shutil.rmtree(path, onerror=_drop_readonly)
    if not path.exists():
        return ""
    aside = path.with_name(f"{path.name}.old-{int(time.time())}")
    try:
        path.rename(aside)
    except OSError as exc:
        return f"{path} could not be removed ({exc})"
    logging.getLogger("memorymap.searxng").warning(
        "Couldn't delete %s, so it was moved to %s. It can be deleted by hand.",
        path,
        aside,
    )
    return ""


def uninstall_source(data_dir: Path) -> dict:
    """Delete the virtualenv and checkout so the next start installs fresh.

    A part-finished install — pip interrupted, a half-cloned checkout, a venv
    built against a Python that has since been upgraded — leaves
    `source_installed` saying yes and the process dying instantly, which reads
    as "it just doesn't work" with nothing to act on. There was no way to get
    back to a clean state short of deleting folders by hand.

    The generated settings.yml is deliberately kept: it holds the instance's
    secret key and any edits the user has made, and it is not what breaks.
    """
    data_dir = Path(data_dir)
    try:
        _stop_source(data_dir)
    except SearxngError:
        pass  # nothing to stop, or it was already gone — either way, carry on
    _pid_file(data_dir).unlink(missing_ok=True)
    _import_ok.discard(str(data_dir))

    removed, failed = [], []
    for path in (_venv_dir(data_dir), _source_dir(data_dir)):
        if not path.exists():
            continue
        problem = _remove_tree(path)
        (failed if problem else removed).append(problem or path.name)
    log_path(data_dir).unlink(missing_ok=True)
    if failed:
        # Reporting a wipe that didn't happen is what let the next install
        # walk into the same broken folder and blame pip for it.
        raise SearxngError(
            "Couldn't clear the old SearXNG install: "
            + "; ".join(failed)
            + ". Close anything using those folders (a file explorer counts) "
            "and try again."
        )
    return {"removed": removed}


def reinstall_source(data_dir: Path) -> dict:
    """Wipe the install and start a fresh one in the background."""
    if _install_state["running"]:
        raise SearxngError("An install is already running — let it finish first.")
    result = uninstall_source(data_dir)
    install_source(data_dir)
    return {**result, "installing": True}


def log_path(data_dir: Path) -> Path:
    """Where SearXNG's own output goes.

    It used to go to DEVNULL, and that is why "SearXNG started but never
    answered. Check the port isn't in use." was the only thing this could ever
    say. A process that dies a second after spawning — a missing dependency, a
    settings file it won't parse, a port already bound — left no trace
    whatsoever, so the message had to guess, and it guessed the same thing
    every time regardless of what actually happened.
    """
    return Path(data_dir) / "searxng" / "searxng.log"


def recent_output(data_dir: Path, lines: int = 12) -> str:
    """The tail of that log, for a failure message and the Logs screen."""
    path = log_path(data_dir)
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    tail = [line for line in text.strip().splitlines() if line.strip()][-lines:]
    return "\n".join(tail)


def _start_source(data_dir: Path) -> dict:
    """Spawn SearXNG from its virtualenv and remember the PID."""
    if not source_installed(data_dir):
        raise SearxngError("SearXNG isn't installed yet.")
    settings = ensure_settings(data_dir)
    env = {
        **os.environ,
        "SEARXNG_SETTINGS_PATH": str(settings),
        "SEARXNG_PORT": str(HOST_PORT),
        "SEARXNG_BIND_ADDRESS": "127.0.0.1",
        "SEARXNG_BASE_URL": f"{BASE_URL}/",
    }
    output = log_path(data_dir)
    output.parent.mkdir(parents=True, exist_ok=True)
    try:
        # Truncated per start, not appended to: the only question this file
        # answers is "why did *this* attempt fail", and a growing file makes
        # that harder to read, not easier.
        handle = output.open("w", encoding="utf-8")
    except OSError as exc:
        raise SearxngError(f"Couldn't open {output.name} to record output: {exc}") from exc
    try:
        process = subprocess.Popen(  # noqa: S603 — fixed args, no shell
            [str(_venv_python(data_dir)), "-m", "searx.webapp"],
            # Only the git path has a checkout to run from; a tarball install
            # lives in site-packages, and passing a directory that isn't there
            # makes Popen fail with a FileNotFoundError that reads as "SearXNG
            # is missing" rather than "that folder is". A leftover folder that
            # is no longer a checkout is not somewhere to run from either.
            cwd=str(src) if is_checkout(src := _source_dir(data_dir)) else None,
            env=env,
            # Both streams into one file, in the order they were written —
            # SearXNG's startup errors go to whichever it feels like.
            stdout=handle,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise SearxngError(f"Couldn't start SearXNG: {exc}") from exc
    finally:
        # The child holds its own duplicate of the descriptor, so closing
        # this one doesn't cut off its output — it just stops us leaking one
        # handle per start.
        handle.close()
    _pid_file(data_dir).write_text(
        json.dumps({"pid": process.pid, "backend": "source"}), encoding="utf-8"
    )
    return {"url": BASE_URL, "started": True, "backend": "source"}


def _stop_source(data_dir: Path) -> dict:
    pid = _read_pid(data_dir)
    _pid_file(data_dir).unlink(missing_ok=True)
    if not pid or not _alive(pid):
        return {"stopped": False}
    try:
        _terminate(pid)
    except OSError as exc:
        raise SearxngError(f"Couldn't stop SearXNG: {exc}") from exc
    # Give it a moment to close its socket before anything rebinds the port.
    for _ in range(20):
        if not _alive(pid):
            break
        time.sleep(0.25)
    return {"stopped": True}


def _run_streaming(
    args: list[str], timeout: int, on_line
) -> subprocess.CompletedProcess:
    """Run a command, handing each line to `on_line` as it is printed.

    `_run` captures output and returns it when the command finishes, which is
    right for a two-second command and useless for a four-minute one: pip
    building lxml prints steadily for minutes and the user saw none of it, so
    a working install and a hung one looked identical. The lines are the
    evidence that something is happening.
    """
    output: list[str] = []
    try:
        process = subprocess.Popen(  # noqa: S603 — fixed args, no shell
            args,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise SearxngError(f"Couldn't run {args[0]}: {exc}") from exc
    deadline = time.time() + timeout
    try:
        for line in process.stdout or []:
            output.append(line)
            on_line(line)
            if time.time() > deadline:
                process.kill()
                raise SearxngError(
                    f"{args[0]} took longer than {timeout}s and was stopped."
                )
        process.wait(timeout=max(1, int(deadline - time.time())))
    except subprocess.TimeoutExpired as exc:
        process.kill()
        raise SearxngError(f"{args[0]} timed out after {timeout}s.") from exc
    finally:
        if process.stdout:
            process.stdout.close()
    return subprocess.CompletedProcess(
        args, process.returncode, stdout="".join(output), stderr=""
    )


def _run(args: list[str], timeout: int = COMMAND_TIMEOUT) -> subprocess.CompletedProcess:
    """Run a setup command. Fixed argument lists only — never a shell."""
    try:
        return subprocess.run(  # noqa: S603 — fixed args, no shell
            args,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise SearxngError(f"Couldn't run {args[0]}: {exc}") from exc


def _docker_state() -> str:
    """'running', 'stopped', or 'absent' for our container."""
    result = _run(
        ["docker", "ps", "-a", "--filter", f"name=^{CONTAINER_NAME}$", "--format", "{{.State}}"]
    )
    state = (result.stdout or "").strip().splitlines()
    if not state:
        return "absent"
    return "running" if state[0].strip() == "running" else "stopped"


def settings_path(data_dir: Path) -> Path:
    """Where the generated settings live (mounted into the container)."""
    return Path(data_dir) / "searxng" / "settings.yml"


def ensure_settings(data_dir: Path) -> Path:
    """Write the settings file once, then leave the user's edits alone."""
    path = settings_path(data_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(
            SETTINGS_TEMPLATE.format(secret=secrets.token_hex(24)), encoding="utf-8"
        )
    return path


def status(data_dir: Path | None = None) -> dict:
    """Everything the settings screen needs to describe the instance."""
    backend = preferred_backend()
    base = {
        "docker": docker_available(),
        "docker_installed": docker_installed(),
        "source": source_available(),
        "backend": backend,
        "url": BASE_URL,
        "installing": _install_state["running"],
        "install_step": _install_state["step"],
        "install_error": _install_state["error"],
        # An install runs for minutes; a step name that doesn't change for
        # four of them is indistinguishable from a hang. The stage numbers
        # give a bar something to move along, and the log is what the tools
        # are printing right now.
        "install_stage": _install_state["stage"],
        "install_stages": _install_state["stages"],
        "install_progress": _install_state["progress"],
        "install_log": list(_install_state["log"]),
        "detail": "",
        # Answered rather than suggested: "check the port isn't in use" is
        # advice that assumes the person can check.
        "port": port_report(),
    }
    if backend is None:
        # "Docker is installed but not started" is a different problem from
        # "Docker isn't installed", and only one of them is fixed by starting
        # Docker Desktop. Saying which saves a pointless install.
        # Defensive: source installs no longer need anything beyond Python, so
        # this is only reached if `source_available` has been overridden.
        detail = (
            "Docker is installed but its daemon isn't running — start Docker "
            "Desktop, or MemoryMap will set SearXNG up in a virtualenv instead."
            if docker_installed()
            else "SearXNG can't be set up automatically here. Point MemoryMap "
            "at a SearXNG you run yourself."
        )
        return {
            **base,
            "state": "absent",
            "responding": False,
            "docker_installed": docker_installed(),
            "detail": detail,
        }
    if backend == "docker":
        state = _docker_state()
    else:
        state = _source_state(Path(data_dir)) if data_dir else "absent"
        if state == "absent" and not base["installing"]:
            base["detail"] = (
                "Docker is installed but not running, so SearXNG will be set "
                "up in a virtualenv of its own instead. The first start takes "
                "a few minutes — or start Docker Desktop and try again."
                if docker_installed()
                else "Docker isn't installed, so SearXNG will be set up in a "
                "virtualenv of its own. The first start takes a few minutes."
            )
    return {
        **base,
        "state": state,
        "responding": websearch.probe_searxng(BASE_URL) if state == "running" else False,
    }


def start(data_dir: Path) -> dict:
    """Start SearXNG whichever way this machine can, and wait for JSON."""
    backend = preferred_backend()
    if backend is None:
        raise SearxngError(
            "SearXNG can't be set up automatically here. Point MemoryMap at a "
            "SearXNG you run yourself."
        )
    if backend == "source":
        return _start_from_source(data_dir)
    return _start_docker(data_dir)


def _start_from_source(data_dir: Path) -> dict:
    """Install on first use (in the background), then spawn the process."""
    if _install_state["error"]:
        error = _install_state["error"]
        _install_state["error"] = ""
        raise SearxngError(error)
    if _install_state["running"]:
        raise SearxngError(
            f"Still setting SearXNG up — {_install_state['step']} "
            "Press Start again when it finishes."
        )
    if not source_installed(data_dir):
        install_source(data_dir)
        raise SearxngError(
            "Setting SearXNG up in its own virtualenv. This takes a few minutes "
            "the first time; press Start again when it's done."
        )
    if _source_state(data_dir) == "running" and websearch.probe_searxng(BASE_URL):
        return {"url": BASE_URL, "started": False, "backend": "source"}
    result = _start_source(data_dir)
    if not _wait_until_ready():
        # Read what it said *before* stopping it — a SIGTERM adds its own
        # lines, and the interesting ones are the earlier ones.
        said = recent_output(data_dir)
        _stop_source(data_dir)
        logging.getLogger("memorymap.searxng").warning(
            "SearXNG didn't answer within %ss. Its own output was:\n%s",
            START_TIMEOUT,
            said or "(nothing — it wrote no output at all)",
        )
        if said:
            raise SearxngError(
                "SearXNG started but never answered. It said:\n\n"
                f"{said}\n\n"
                f"The full log is at {log_path(data_dir)}."
            )
        raise SearxngError(
            "SearXNG started but wrote nothing and never answered — which "
            "usually means the process died immediately. Check that port "
            f"{HOST_PORT} is free. The log is at {log_path(data_dir)}."
        )
    return result


def _start_docker(data_dir: Path) -> dict:
    """Start (or create) the container and wait until it answers JSON."""
    state = _docker_state()
    if state == "running":
        if websearch.probe_searxng(BASE_URL):
            return {"url": BASE_URL, "started": False}
    elif state == "stopped":
        result = _run(["docker", "start", CONTAINER_NAME])
        if result.returncode != 0:
            raise SearxngError(_reason(result, "Couldn't start the existing container"))
    else:
        settings = ensure_settings(data_dir)
        result = _run(
            [
                "docker", "run", "-d",
                "--name", CONTAINER_NAME,
                "--restart", "unless-stopped",
                "-p", f"{HOST_PORT}:8080",
                "-v", f"{settings}:/etc/searxng/settings.yml:ro",
                "-e", f"SEARXNG_BASE_URL={BASE_URL}/",
                IMAGE,
            ],
            timeout=START_TIMEOUT,
        )
        if result.returncode != 0:
            raise SearxngError(_reason(result, "Couldn't create the container"))

    if not _wait_until_ready():
        raise SearxngError(
            "SearXNG started but isn't answering yet. Give it a moment and press "
            "Auto-detect, or check `docker logs memorymap-searxng`."
        )
    return {"url": BASE_URL, "started": True}


def stop(data_dir: Path | None = None) -> dict:
    """Stop the instance but keep it (and its settings) for next time."""
    backend = preferred_backend()
    if backend is None:
        raise SearxngError("There is no SearXNG here that MemoryMap started.")
    if backend == "source":
        if data_dir is None:
            raise SearxngError("Couldn't find the SearXNG install.")
        return _stop_source(Path(data_dir))
    if _docker_state() == "absent":
        return {"stopped": False}
    result = _run(["docker", "stop", CONTAINER_NAME], timeout=40)
    if result.returncode != 0:
        raise SearxngError(_reason(result, "Couldn't stop the container"))
    return {"stopped": True}


def _wait_until_ready(timeout: int = START_TIMEOUT) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if websearch.probe_searxng(BASE_URL):
            return True
        time.sleep(2)
    return False


# Lines that are never the reason something failed, however last they are.
#
# Reported with a screenshot: "Couldn't install SearXNG: [notice] To update,
# run: …python.exe -m pip install --upgrade pip". That notice is pip's parting
# advice, it is printed on almost every run, and it is always the last line —
# so taking the last line meant reporting it instead of the actual failure,
# every single time an install went wrong. The user is then sent to fix pip,
# which was never the problem.
_NOT_A_REASON = (
    "[notice]",
    "to update, run",
    "you should consider upgrading",
    "warning: you are using pip version",
)


def _reason(result: subprocess.CompletedProcess, prefix: str) -> str:
    """`prefix`, plus the most useful line the command actually printed.

    Prefers a line that names an error, falls back to the last line that isn't
    boilerplate, and says nothing rather than something misleading.
    """
    lines = [
        line.strip()
        for line in (result.stderr or result.stdout or "").strip().splitlines()
        if line.strip()
    ]
    useful = [
        line
        for line in lines
        if not any(marker in line.lower() for marker in _NOT_A_REASON)
    ]
    if not useful:
        return prefix

    # A line that names the failure beats the last line — pip prints the real
    # cause and then several lines of hint after it.
    named = [
        line
        for line in useful
        if line.lower().startswith(("error", "fatal", "exception"))
        or "error:" in line.lower()
    ]
    return f"{prefix}: {(named or useful)[-1]}"
