"""Run a SearXNG instance for the user (optional).

SearXNG is a separate service — it can't be imported into this process — but
the app can still own its lifecycle so "use SearXNG" is a button rather than a
setup guide. We generate a settings file that enables the JSON API (the one
step people always miss), start it, wait for it to answer, and hand back the
URL.

There are two ways to run it, and Docker is only the tidier one:

- **docker** — pull the official image and run a container. Preferred when
  Docker is installed, because upgrades and isolation come for free.
- **source** — SearXNG is a Python app, so it also runs in a virtualenv of its
  own under the data directory, started as a child process. Slower to set up
  (a pip install from git) and it needs `git`, but it needs no Docker at all.

Everything degrades: no backend available, or a failed start, returns a plain
reason and leaves web search on DuckDuckGo.
"""

from __future__ import annotations

import json
import logging
import os
import secrets
import shutil
import signal
import socket
import subprocess
import sys
import threading
import time
from pathlib import Path

from memorymap.search import websearch

CONTAINER_NAME = "memorymap-searxng"
IMAGE = "searxng/searxng:latest"
HOST_PORT = 8888
BASE_URL = f"http://localhost:{HOST_PORT}"
START_TIMEOUT = 90  # image pulls can be slow the first time
COMMAND_TIMEOUT = 20

SOURCE_REPO = "https://github.com/searxng/searxng.git"
# The same code as a tarball, for machines without the git binary. pip can
# download and unpack this itself, which is what makes a no-Docker-no-git
# install possible at all.
SOURCE_TARBALL = "https://github.com/searxng/searxng/archive/refs/heads/master.tar.gz"
INSTALL_TIMEOUT = 900  # a cold pip install from git builds a few wheels

# use_default_settings keeps SearXNG's own defaults and layers ours on top —
# the important bit being the json format, without which the API returns 403.
SETTINGS_TEMPLATE = """# Generated by MemoryMap. Edit freely; it is not overwritten once created.
use_default_settings: true
server:
  secret_key: "{secret}"
  limiter: false
  image_proxy: true
search:
  safe_search: 0
  formats:
    - html
    - json
"""


class SearxngError(RuntimeError):
    """Something stopped us managing the instance."""


# `docker info` against a stopped daemon is quick to fail, but give it room on
# a cold Docker Desktop rather than calling a slow start "not running".
DAEMON_PROBE_TIMEOUT = 8


def docker_installed() -> bool:
    """Is the docker command on PATH? Says nothing about the daemon."""
    return shutil.which("docker") is not None


def docker_available() -> bool:
    """Can we actually run a container right now?

    Checking only that the binary exists was wrong, and produced exactly the
    failure it should have prevented: with Docker Desktop installed but not
    started, the app picked the Docker backend, tried to create a container,
    and reported "failed to connect to the docker API at npipe:..." — while
    the from-source backend that would have worked was never considered.

    `docker info` is the cheapest question that means "is the daemon up".
    """
    if not docker_installed():
        return False
    try:
        result = subprocess.run(  # noqa: S603 — fixed args, no shell
            ["docker", "info", "--format", "{{.ServerVersion}}"],
            capture_output=True,
            text=True,
            timeout=DAEMON_PROBE_TIMEOUT,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return result.returncode == 0


def git_installed() -> bool:
    """Is the git binary on PATH? Only decides *how* we fetch, not whether."""
    return shutil.which("git") is not None


def source_available() -> bool:
    """True if we could build a virtualenv and fetch SearXNG into it.

    Always true now. It used to require the `git` binary, which meant a
    machine with neither Docker nor git could not install SearXNG at all —
    "I can't download searxng", with the UI offering a button that could
    never work. pip fetches and unpacks a source tarball over HTTPS without
    git's help, so the only real requirements are Python (we are running on
    it) and a network connection, which any install needs anyway.

    Deliberately not a `pip install searxng` from PyPI: SearXNG does not
    publish itself there, so that name is somebody else's package, and
    installing it would be running an unknown author's code because the name
    looked right.
    """
    return True


def preferred_backend() -> str | None:
    """Which way we'd run it: docker if present, else from source."""
    if docker_available():
        return "docker"
    if source_available():
        return "source"
    return None


# --- running from source ------------------------------------------------------

# Progress for the one install that can be running at a time. The install is
# minutes long, so it happens on a worker thread and the settings screen polls
# status() rather than holding a request open.
_install_lock = threading.Lock()
_install_state: dict = {"running": False, "step": "", "error": ""}


def _source_dir(data_dir: Path) -> Path:
    return Path(data_dir) / "searxng" / "src"


def _venv_dir(data_dir: Path) -> Path:
    return Path(data_dir) / "searxng" / "venv"


def _venv_python(data_dir: Path) -> Path:
    venv = _venv_dir(data_dir)
    return venv / ("Scripts/python.exe" if os.name == "nt" else "bin/python")


def _pid_file(data_dir: Path) -> Path:
    return Path(data_dir) / "searxng" / "run.json"


def source_installed(data_dir: Path) -> bool:
    """Is SearXNG present in its own virtualenv?

    The checkout directory only exists on the git path — a tarball install
    puts `searx` straight into the venv's site-packages and never creates
    one. So the question that actually matters is whether the venv can
    import `searx`, not whether a source folder is sitting there.
    """
    python = _venv_python(data_dir)
    if not python.exists():
        return False
    if _source_dir(data_dir).exists():
        return True
    result = _run([str(python), "-c", "import searx"], timeout=COMMAND_TIMEOUT)
    return result.returncode == 0


def _read_pid(data_dir: Path) -> int | None:
    try:
        record = json.loads(_pid_file(data_dir).read_text(encoding="utf-8"))
        return int(record.get("pid")) or None
    except (OSError, ValueError, TypeError):
        return None


def _alive(pid: int) -> bool:
    """Is this PID still around? Signal 0 checks without touching the process."""
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def _source_state(data_dir: Path) -> str:
    """'running', 'stopped', or 'absent' for the from-source instance."""
    if not source_installed(data_dir):
        return "absent"
    pid = _read_pid(data_dir)
    return "running" if pid and _alive(pid) else "stopped"


def install_source(data_dir: Path) -> None:
    """Clone SearXNG into a virtualenv of its own. Minutes, not seconds."""
    with _install_lock:
        if _install_state["running"]:
            raise SearxngError("An install is already running.")
        _install_state.update({"running": True, "step": "Creating a virtualenv…", "error": ""})

    def work() -> None:
        try:
            src = _source_dir(data_dir)
            src.parent.mkdir(parents=True, exist_ok=True)
            venv = _venv_dir(data_dir)
            if not _venv_python(data_dir).exists():
                _run([sys.executable, "-m", "venv", str(venv)], timeout=180)
            _install_state["step"] = "Downloading SearXNG…"
            # With git, clone and install editable: the checkout can be
            # updated later without redownloading. Without git, pip fetches
            # the tarball itself — slower to update, but it works on a
            # machine that has neither Docker nor git, which previously had
            # no way to install SearXNG at all.
            if git_installed():
                if not src.exists():
                    result = _run(
                        ["git", "clone", "--depth", "1", SOURCE_REPO, str(src)],
                        timeout=INSTALL_TIMEOUT,
                    )
                    if result.returncode != 0:
                        raise SearxngError(_reason(result, "Couldn't download SearXNG"))
                target = ["-e", str(src)]
            else:
                target = [SOURCE_TARBALL]
            _install_state["step"] = "Installing dependencies (this takes a few minutes)…"
            result = _run(
                [str(_venv_python(data_dir)), "-m", "pip", "install", *target],
                timeout=INSTALL_TIMEOUT,
            )
            if result.returncode != 0:
                raise SearxngError(_reason(result, "Couldn't install SearXNG"))
            _install_state["step"] = ""
        except SearxngError as exc:
            _install_state["error"] = str(exc)
        except Exception as exc:  # noqa: BLE001 — a worker thread must not die silently
            _install_state["error"] = f"Install failed: {exc}"
        finally:
            _install_state["running"] = False

    threading.Thread(target=work, name="searxng-install", daemon=True).start()


def port_report() -> dict:
    """Who, if anyone, is holding the port SearXNG wants.

    "Check the port isn't in use" is advice that assumes the person can check.
    This checks: it binds the port, and if it can't, asks whatever is there
    whether it speaks SearXNG. Those are three genuinely different situations
    — free, occupied by a working SearXNG, occupied by something else — and
    only the last one is a problem the user has to go and solve.
    """
    free = True
    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        # No SO_REUSEADDR: the question is whether a *live* listener holds the
        # port, and reuse would let this bind alongside one on some platforms.
        probe.bind(("127.0.0.1", HOST_PORT))
        probe.close()
    except OSError:
        free = False

    if free:
        return {
            "port": HOST_PORT,
            "free": True,
            "held_by_searxng": False,
            "detail": f"Port {HOST_PORT} is free.",
        }

    answering = websearch.probe_searxng(BASE_URL)
    return {
        "port": HOST_PORT,
        "free": False,
        "held_by_searxng": answering,
        "detail": (
            f"A working SearXNG is already answering on port {HOST_PORT} — "
            "MemoryMap can use it as it is."
            if answering
            else f"Something is using port {HOST_PORT}, and it isn't answering "
            "as SearXNG. Close whatever has it (or stop and reinstall here to "
            "clear a half-dead instance of our own) and try again."
        ),
    }


def uninstall_source(data_dir: Path) -> dict:
    """Delete the virtualenv and checkout so the next start installs fresh.

    A part-finished install — pip interrupted, a half-cloned checkout, a venv
    built against a Python that has since been upgraded — leaves
    `source_installed` saying yes and the process dying instantly, which reads
    as "it just doesn't work" with nothing to act on. There was no way to get
    back to a clean state short of deleting folders by hand.

    The generated settings.yml is deliberately kept: it holds the instance's
    secret key and any edits the user has made, and it is not what breaks.
    """
    data_dir = Path(data_dir)
    try:
        _stop_source(data_dir)
    except SearxngError:
        pass  # nothing to stop, or it was already gone — either way, carry on
    _pid_file(data_dir).unlink(missing_ok=True)

    removed = []
    for path in (_venv_dir(data_dir), _source_dir(data_dir)):
        if path.exists():
            shutil.rmtree(path, ignore_errors=True)
            removed.append(path.name)
    log_path(data_dir).unlink(missing_ok=True)
    return {"removed": removed}


def reinstall_source(data_dir: Path) -> dict:
    """Wipe the install and start a fresh one in the background."""
    if _install_state["running"]:
        raise SearxngError("An install is already running — let it finish first.")
    result = uninstall_source(data_dir)
    install_source(data_dir)
    return {**result, "installing": True}


def log_path(data_dir: Path) -> Path:
    """Where SearXNG's own output goes.

    It used to go to DEVNULL, and that is why "SearXNG started but never
    answered. Check the port isn't in use." was the only thing this could ever
    say. A process that dies a second after spawning — a missing dependency, a
    settings file it won't parse, a port already bound — left no trace
    whatsoever, so the message had to guess, and it guessed the same thing
    every time regardless of what actually happened.
    """
    return Path(data_dir) / "searxng" / "searxng.log"


def recent_output(data_dir: Path, lines: int = 12) -> str:
    """The tail of that log, for a failure message and the Logs screen."""
    path = log_path(data_dir)
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    tail = [line for line in text.strip().splitlines() if line.strip()][-lines:]
    return "\n".join(tail)


def _start_source(data_dir: Path) -> dict:
    """Spawn SearXNG from its virtualenv and remember the PID."""
    if not source_installed(data_dir):
        raise SearxngError("SearXNG isn't installed yet.")
    settings = ensure_settings(data_dir)
    env = {
        **os.environ,
        "SEARXNG_SETTINGS_PATH": str(settings),
        "SEARXNG_PORT": str(HOST_PORT),
        "SEARXNG_BIND_ADDRESS": "127.0.0.1",
        "SEARXNG_BASE_URL": f"{BASE_URL}/",
    }
    output = log_path(data_dir)
    output.parent.mkdir(parents=True, exist_ok=True)
    try:
        # Truncated per start, not appended to: the only question this file
        # answers is "why did *this* attempt fail", and a growing file makes
        # that harder to read, not easier.
        handle = output.open("w", encoding="utf-8")
    except OSError as exc:
        raise SearxngError(f"Couldn't open {output.name} to record output: {exc}") from exc
    try:
        process = subprocess.Popen(  # noqa: S603 — fixed args, no shell
            [str(_venv_python(data_dir)), "-m", "searx.webapp"],
            # Only the git path has a checkout to run from; a tarball install
            # lives in site-packages, and passing a directory that isn't there
            # makes Popen fail with a FileNotFoundError that reads as "SearXNG
            # is missing" rather than "that folder is".
            cwd=str(src) if (src := _source_dir(data_dir)).exists() else None,
            env=env,
            # Both streams into one file, in the order they were written —
            # SearXNG's startup errors go to whichever it feels like.
            stdout=handle,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise SearxngError(f"Couldn't start SearXNG: {exc}") from exc
    finally:
        # The child holds its own duplicate of the descriptor, so closing
        # this one doesn't cut off its output — it just stops us leaking one
        # handle per start.
        handle.close()
    _pid_file(data_dir).write_text(
        json.dumps({"pid": process.pid, "backend": "source"}), encoding="utf-8"
    )
    return {"url": BASE_URL, "started": True, "backend": "source"}


def _stop_source(data_dir: Path) -> dict:
    pid = _read_pid(data_dir)
    _pid_file(data_dir).unlink(missing_ok=True)
    if not pid or not _alive(pid):
        return {"stopped": False}
    try:
        os.kill(pid, signal.SIGTERM)
    except OSError as exc:
        raise SearxngError(f"Couldn't stop SearXNG: {exc}") from exc
    # Give it a moment to close its socket before anything rebinds the port.
    for _ in range(20):
        if not _alive(pid):
            break
        time.sleep(0.25)
    return {"stopped": True}


def _run(args: list[str], timeout: int = COMMAND_TIMEOUT) -> subprocess.CompletedProcess:
    """Run a setup command. Fixed argument lists only — never a shell."""
    try:
        return subprocess.run(  # noqa: S603 — fixed args, no shell
            args,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise SearxngError(f"Couldn't run {args[0]}: {exc}") from exc


def _docker_state() -> str:
    """'running', 'stopped', or 'absent' for our container."""
    result = _run(
        ["docker", "ps", "-a", "--filter", f"name=^{CONTAINER_NAME}$", "--format", "{{.State}}"]
    )
    state = (result.stdout or "").strip().splitlines()
    if not state:
        return "absent"
    return "running" if state[0].strip() == "running" else "stopped"


def settings_path(data_dir: Path) -> Path:
    """Where the generated settings live (mounted into the container)."""
    return Path(data_dir) / "searxng" / "settings.yml"


def ensure_settings(data_dir: Path) -> Path:
    """Write the settings file once, then leave the user's edits alone."""
    path = settings_path(data_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists():
        path.write_text(
            SETTINGS_TEMPLATE.format(secret=secrets.token_hex(24)), encoding="utf-8"
        )
    return path


def status(data_dir: Path | None = None) -> dict:
    """Everything the settings screen needs to describe the instance."""
    backend = preferred_backend()
    base = {
        "docker": docker_available(),
        "docker_installed": docker_installed(),
        "source": source_available(),
        "backend": backend,
        "url": BASE_URL,
        "installing": _install_state["running"],
        "install_step": _install_state["step"],
        "install_error": _install_state["error"],
        "detail": "",
        # Answered rather than suggested: "check the port isn't in use" is
        # advice that assumes the person can check.
        "port": port_report(),
    }
    if backend is None:
        # "Docker is installed but not started" is a different problem from
        # "Docker isn't installed", and only one of them is fixed by starting
        # Docker Desktop. Saying which saves a pointless install.
        # Defensive: source installs no longer need anything beyond Python, so
        # this is only reached if `source_available` has been overridden.
        detail = (
            "Docker is installed but its daemon isn't running — start Docker "
            "Desktop, or MemoryMap will set SearXNG up in a virtualenv instead."
            if docker_installed()
            else "SearXNG can't be set up automatically here. Point MemoryMap "
            "at a SearXNG you run yourself."
        )
        return {
            **base,
            "state": "absent",
            "responding": False,
            "docker_installed": docker_installed(),
            "detail": detail,
        }
    if backend == "docker":
        state = _docker_state()
    else:
        state = _source_state(Path(data_dir)) if data_dir else "absent"
        if state == "absent" and not base["installing"]:
            base["detail"] = (
                "Docker is installed but not running, so SearXNG will be set "
                "up in a virtualenv of its own instead. The first start takes "
                "a few minutes — or start Docker Desktop and try again."
                if docker_installed()
                else "Docker isn't installed, so SearXNG will be set up in a "
                "virtualenv of its own. The first start takes a few minutes."
            )
    return {
        **base,
        "state": state,
        "responding": websearch.probe_searxng(BASE_URL) if state == "running" else False,
    }


def start(data_dir: Path) -> dict:
    """Start SearXNG whichever way this machine can, and wait for JSON."""
    backend = preferred_backend()
    if backend is None:
        raise SearxngError(
            "SearXNG can't be set up automatically here. Point MemoryMap at a "
            "SearXNG you run yourself."
        )
    if backend == "source":
        return _start_from_source(data_dir)
    return _start_docker(data_dir)


def _start_from_source(data_dir: Path) -> dict:
    """Install on first use (in the background), then spawn the process."""
    if _install_state["error"]:
        error = _install_state["error"]
        _install_state["error"] = ""
        raise SearxngError(error)
    if _install_state["running"]:
        raise SearxngError(
            f"Still setting SearXNG up — {_install_state['step']} "
            "Press Start again when it finishes."
        )
    if not source_installed(data_dir):
        install_source(data_dir)
        raise SearxngError(
            "Setting SearXNG up in its own virtualenv. This takes a few minutes "
            "the first time; press Start again when it's done."
        )
    if _source_state(data_dir) == "running" and websearch.probe_searxng(BASE_URL):
        return {"url": BASE_URL, "started": False, "backend": "source"}
    result = _start_source(data_dir)
    if not _wait_until_ready():
        # Read what it said *before* stopping it — a SIGTERM adds its own
        # lines, and the interesting ones are the earlier ones.
        said = recent_output(data_dir)
        _stop_source(data_dir)
        logging.getLogger("memorymap.searxng").warning(
            "SearXNG didn't answer within %ss. Its own output was:\n%s",
            START_TIMEOUT,
            said or "(nothing — it wrote no output at all)",
        )
        if said:
            raise SearxngError(
                "SearXNG started but never answered. It said:\n\n"
                f"{said}\n\n"
                f"The full log is at {log_path(data_dir)}."
            )
        raise SearxngError(
            "SearXNG started but wrote nothing and never answered — which "
            "usually means the process died immediately. Check that port "
            f"{HOST_PORT} is free. The log is at {log_path(data_dir)}."
        )
    return result


def _start_docker(data_dir: Path) -> dict:
    """Start (or create) the container and wait until it answers JSON."""
    state = _docker_state()
    if state == "running":
        if websearch.probe_searxng(BASE_URL):
            return {"url": BASE_URL, "started": False}
    elif state == "stopped":
        result = _run(["docker", "start", CONTAINER_NAME])
        if result.returncode != 0:
            raise SearxngError(_reason(result, "Couldn't start the existing container"))
    else:
        settings = ensure_settings(data_dir)
        result = _run(
            [
                "docker", "run", "-d",
                "--name", CONTAINER_NAME,
                "--restart", "unless-stopped",
                "-p", f"{HOST_PORT}:8080",
                "-v", f"{settings}:/etc/searxng/settings.yml:ro",
                "-e", f"SEARXNG_BASE_URL={BASE_URL}/",
                IMAGE,
            ],
            timeout=START_TIMEOUT,
        )
        if result.returncode != 0:
            raise SearxngError(_reason(result, "Couldn't create the container"))

    if not _wait_until_ready():
        raise SearxngError(
            "SearXNG started but isn't answering yet. Give it a moment and press "
            "Auto-detect, or check `docker logs memorymap-searxng`."
        )
    return {"url": BASE_URL, "started": True}


def stop(data_dir: Path | None = None) -> dict:
    """Stop the instance but keep it (and its settings) for next time."""
    backend = preferred_backend()
    if backend is None:
        raise SearxngError("Neither Docker nor git is installed.")
    if backend == "source":
        if data_dir is None:
            raise SearxngError("Couldn't find the SearXNG install.")
        return _stop_source(Path(data_dir))
    if _docker_state() == "absent":
        return {"stopped": False}
    result = _run(["docker", "stop", CONTAINER_NAME], timeout=40)
    if result.returncode != 0:
        raise SearxngError(_reason(result, "Couldn't stop the container"))
    return {"stopped": True}


def _wait_until_ready(timeout: int = START_TIMEOUT) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if websearch.probe_searxng(BASE_URL):
            return True
        time.sleep(2)
    return False


def _reason(result: subprocess.CompletedProcess, prefix: str) -> str:
    detail = (result.stderr or result.stdout or "").strip().splitlines()
    return f"{prefix}: {detail[-1]}" if detail else prefix
