"""Alembic environment — wired to the app's own engine, not a second config.

Deliberately does **not** replace `DatabaseManager`'s existing
`create_all()` + additive auto-migrator (`core/database.py`): those stay
exactly as they are, for fresh installs and simple column additions, the
same as before this file existed. What this adds is the piece they were
never able to do — a real rename or drop — for the day one is actually
needed. See `core/database.py`'s own docstring and `migrations/README.md`
(next to this file) for the adoption story: every existing database is
*stamped* to the baseline revision at startup, never migrated into it,
because its schema already matches (create_all() built it). A brand-new
database is stamped too, for the same reason. Nothing here runs DDL against
a database that didn't ask for it by having a newer revision available.
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

from memorymap.core.config import ConfigManager
from memorymap.core.database import Base

config = context.config

if config.config_file_name is not None:
    # `disable_existing_loggers` defaults to True, which is fine for a
    # human running `alembic` as its own short-lived process — but this now
    # also runs *inside* the app's own long-lived process
    # (`_ensure_alembic_baseline`, core/database.py) and inside the test
    # suite (tests/test_alembic_baseline.py calls it directly). True there
    # silently disabled every logger the app had already configured for the
    # rest of that process's life — caught by a cluster of unrelated
    # logging-dependent tests (test_extras, test_log_console,
    # test_security_hardening, test_websearch_diagnosis) failing only when
    # run as part of the full suite, never in isolation: proof the damage
    # was global state left behind by an earlier test, not a bug in any of
    # those tests themselves.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata


_PLACEHOLDER_URL = "driver://user:pass@localhost/dbname"


def _db_url() -> str:
    # A caller that already knows exactly which database it means —
    # `DatabaseManager`, from Python, one call per real db_path it was
    # constructed with — sets `sqlalchemy.url` on the Config object before
    # invoking `command.stamp`/`command.upgrade`. Deferring to that value
    # when it's present, rather than always re-deriving one here, is what
    # keeps this safe for the test suite: dozens of tests construct
    # `DatabaseManager(some_tmp_path)` with no relation to
    # `MEMORYMAP_DATA_DIR` at all, and re-resolving via ConfigManager()
    # unconditionally would run Alembic against the wrong file — the real
    # app's data dir — instead of each test's own throwaway one.
    #
    # Only a human running `alembic` directly from a terminal (nothing sets
    # `sqlalchemy.url` first) falls through to ConfigManager()'s own
    # resolution — the same MEMORYMAP_DATA_DIR / platform-default order the
    # app itself uses, so a manually-run migration still lands on the real
    # database.
    explicit = config.get_main_option("sqlalchemy.url")
    if explicit and explicit != _PLACEHOLDER_URL:
        return explicit
    db_path = ConfigManager().db_path
    return f"sqlite:///{db_path}"


def run_migrations_offline() -> None:
    context.configure(
        url=_db_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = _db_url()
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        # SQLite can't ALTER most column properties in place — every
        # autogenerated migration needs batch mode to do it via a
        # rebuild-and-swap instead. Set once here rather than in every
        # migration file.
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
