// INBOX 736 measured: Stop's state after a run ends, with and without a
// pending timer, and the output panel's grip (drag, keys, kept per document).
// Usage: BASE=http://127.0.0.1:8846 node docs42c.js
const { boot } = require("./lib.js");
const J = JSON.stringify;
let bad = 0;
const ok = (n, c, d) => { if (!c) bad += 1; console.log(`${c ? "PASS" : "FAIL"}  ${n}  - ${d}`); };
(async () => {
  const { browser, page } = await boot();
  await page.evaluate(() => switchTab("documents"));
  await page.waitForTimeout(1500);
  const open = (c) => page.evaluate(async (c) => { const d = await apiJson("/documents", { method: "POST", body: JSON.stringify({ title: "run.js", content: c, file_type: "js" }) }); await loadDocuments(d.id); return d.id; }, c);
  const state = () => page.evaluate(() => { const p = document.querySelector(".cm-run-panel"); const stop = [...p.querySelectorAll("button")].find((b) => /Stop/.test(b.textContent)); return { status: p.querySelector(".cm-run-status").textContent, stop: stop.disabled ? "disabled" : "enabled", rows: p.querySelectorAll(".cm-run-row").length }; });
  await open("console.log('one');\n");
  await page.waitForTimeout(2000);
  await page.evaluate(() => docRunCode());
  await page.waitForTimeout(1500);
  const a = await state();
  ok("a script that ends: Finished. and Stop disabled", a.status === "Finished." && a.stop === "disabled", J(a));
  const id = await open("setTimeout(() => console.log('late'), 600);\n");
  await page.waitForTimeout(2000);
  await page.evaluate(() => docRunCode());
  await page.waitForTimeout(250);
  const b1 = await state();
  await page.waitForTimeout(1200);
  const b2 = await state();
  ok("a pending timer keeps Stop until it fires, then Finished.", b1.stop === "enabled" && b2.status === "Finished." && b2.stop === "disabled" && b2.rows === 1, J([b1, b2]));
  const h0 = await page.evaluate(() => Math.round(document.querySelector(".cm-run-panel").getBoundingClientRect().height));
  const grip = await page.evaluate(() => { const g = document.querySelector(".doc-run-resize"); const r = g.getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2, h: Math.round(r.height), w: Math.round(r.width), cursor: getComputedStyle(g).cursor }; });
  await page.mouse.move(grip.x, grip.y);
  await page.mouse.down();
  await page.mouse.move(grip.x, grip.y - 120, { steps: 6 });
  await page.mouse.up();
  const h1 = await page.evaluate(() => Math.round(document.querySelector(".cm-run-panel").getBoundingClientRect().height));
  ok("dragging the grip up 120px makes the panel 120px taller", Math.abs(h1 - h0 - 120) <= 2, J({ h0, h1, grip }));
  await page.focus(".doc-run-resize");
  await page.keyboard.press("ArrowDown");
  const h2 = await page.evaluate(() => Math.round(document.querySelector(".cm-run-panel").getBoundingClientRect().height));
  ok("ArrowDown steps it 16px shorter", h1 - h2 === 16, J({ h1, h2 }));
  await page.evaluate(() => docRunClose());
  await open("console.log(2);\n");
  await page.waitForTimeout(1500);
  await page.evaluate(async (id) => { await loadDocuments(id); }, id);
  await page.waitForTimeout(1500);
  await page.evaluate(() => docRunCode());
  await page.waitForTimeout(600);
  const h3 = await page.evaluate(() => Math.round(document.querySelector(".cm-run-panel").getBoundingClientRect().height));
  ok("the height is kept for that document", h3 === h2, J({ h2, h3 }));
  console.log("bad", bad);
  await browser.close();
})();
