"""baseline: current schema

Revision ID: 8a8a14407cc0
Revises: 
Create Date: 2026-08-24 20:58:00.725419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import memorymap.core.database


# revision identifiers, used by Alembic.
#
# CodeQL flags all four as "unused global variable" — true from a plain
# read of this file, but wrong about what's happening: Alembic's own
# ScriptDirectory reads them off the loaded module by attribute name
# (script.py.mako generates exactly this shape for every migration in
# every Alembic project), never through an import anywhere in this repo.
# __all__ documents that without changing any behaviour — it only affects
# `from module import *`, which nothing here does.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on"]
revision: str = '8a8a14407cc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('raw_result_ids', sa.Text(), nullable=False),
    sa.Column('search_mode', sa.String(length=40), nullable=False),
    sa.Column('when_phrase', sa.String(length=120), nullable=False),
    sa.Column('match_info', sa.Text(), nullable=False),
    sa.Column('connected_ids', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(), server_default='default', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ask_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ask_turns_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(), server_default='default', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('updated_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(), server_default='default', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('updated_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.String(), server_default='default', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=140), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kdf_salt', sa.LargeBinary(length=32), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(length=128), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('ai_confidence', sa.Integer(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('user_filed', sa.Boolean(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('updated_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('archived_at', memorymap.core.database.DateTime(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', memorymap.core.database.DateTime(), nullable=True),
    sa.Column('entities_extracted_at', memorymap.core.database.DateTime(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.String(), server_default='default', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_table('document_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_links_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_links_entry_id'), ['entry_id'], unique=False)

    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=200), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_table('entity_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=60), nullable=False),
    sa.Column('at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('precision', sa.String(length=10), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_dates_entry_id'), ['entry_id'], unique=False)

    op.create_table('entry_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_entry_id', sa.Integer(), nullable=False),
    sa.Column('target_entry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reason_confidence', sa.Float(), nullable=True),
    sa.Column('link_type', sa.String(length=24), nullable=True),
    sa.Column('workspace_id', sa.String(), server_default='default', nullable=False),
    sa.ForeignKeyConstraint(['source_entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['target_entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_links_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('entry_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entry_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entry_revisions_entry_id'), ['entry_id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('due_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('recurring', sa.String(length=10), nullable=False),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whiteboard_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.Column('group_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('updated_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whiteboard_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whiteboard_nodes_group_id'), ['group_id'], unique=False)

    op.create_table('whiteboard_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=True),
    sa.Column('group_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('updated_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whiteboard_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whiteboard_objects_group_id'), ['group_id'], unique=False)

    op.create_table('whiteboard_sketches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', memorymap.core.database.DateTime(), nullable=False),
    sa.Column('updated_at', memorymap.core.database.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whiteboard_sketches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whiteboard_sketches_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiteboard_sketches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whiteboard_sketches_group_id'))

    op.drop_table('whiteboard_sketches')
    with op.batch_alter_table('whiteboard_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whiteboard_objects_group_id'))

    op.drop_table('whiteboard_objects')
    with op.batch_alter_table('whiteboard_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whiteboard_nodes_group_id'))

    op.drop_table('whiteboard_nodes')
    op.drop_table('reminders')
    with op.batch_alter_table('entry_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_revisions_entry_id'))

    op.drop_table('entry_revisions')
    with op.batch_alter_table('entry_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_links_workspace_id'))

    op.drop_table('entry_links')
    with op.batch_alter_table('entry_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entry_dates_entry_id'))

    op.drop_table('entry_dates')
    op.drop_table('entity_mentions')
    op.drop_table('embeddings')
    with op.batch_alter_table('document_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_links_entry_id'))
        batch_op.drop_index(batch_op.f('ix_document_links_document_id'))

    op.drop_table('document_links')
    op.drop_table('attachments')
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_workspace_id'))

    op.drop_table('entries')
    op.drop_table('vault')
    op.drop_table('users')
    op.drop_table('user_preferences')
    op.drop_table('spaces')
    op.drop_table('media_uploads')
    op.drop_table('entities')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_workspace_id'))

    op.drop_table('documents')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_workspace_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_workspace_id'))

    op.drop_table('categories')
    op.drop_table('audit_log')
    with op.batch_alter_table('ask_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ask_turns_workspace_id'))

    op.drop_table('ask_turns')
    # ### end Alembic commands ###
