"""A deterministic notebook of `count` notes with one of everything the
folder export carries (WORLD_CLASS_PLAN 25b, Brief 48): categories with a
colour, tags, pins, archived, binned and draft notes, a parent, graph pins,
source fields, properties, links with a kind and props, reminders on notes
and on a document, attachments (two with the same name on one note),
documents linked to notes, and boards with cards, a drawing and nested
shapes.

Generated by the test that needs it, never committed as data
(`test_scratchpad_size.py`; the repo's size). Every value comes from the
note's index, so two builds are the same notebook.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timedelta
from pathlib import Path

CATEGORIES = [("Garden", "#5a8f3c", "Beds, seeds and the shed"), ("Work", None, None), ("Travel", "#3c6e8f", None),
              ("Reading", None, "Books and papers"), ("Journal", None, None)]
BASE = datetime(2024, 3, 14, 9, 30)


def _content(i: int) -> str:
    text = f"Note {i} about harbour pilots, tides and the {['north', 'south', 'east'][i % 3]} quay.\n\nSecond paragraph {i}."
    if i % 11 == 0:
        text = f"---\nstatus: draft {i}\nowner: Ana\n---\n{text}"
    if i % 6 == 0:
        text += f"\n\nSee [[Note {i + 1}]]."
    return text


def _note(session, i: int):  # noqa: ANN001, ANN202
    from memorymap.entry import manager

    name = CATEGORIES[i % len(CATEGORIES)][0]
    entry = manager.create_entry(session, _content(i), category_name=name, tags=[f"tag{i % 7}", "shared"] if i % 4 else [],
                                 ai_confidence=i % 101)
    entry.created_at = BASE + timedelta(hours=7 * i)
    entry.edited_at = entry.created_at + timedelta(minutes=5) if i % 5 == 0 else None
    entry.pinned = i % 7 == 0
    entry.user_filed = i % 2 == 0
    entry.archived_at = entry.created_at + timedelta(days=2) if i % 23 == 0 else None
    entry.is_deleted = i % 31 == 0
    entry.deleted_at = entry.created_at + timedelta(days=3) if i % 31 == 0 else None
    entry.is_draft = i % 41 == 0
    entry.source_url = f"https://example.org/{i}" if i % 13 == 0 else None
    entry.source_title = f"Page {i}" if i % 13 == 0 else None
    entry.source_path = f"obsidian:Vault/{i}.md" if i % 29 == 0 else ""
    entry.map_topic = i % 37 == 0
    entry.graph_pin_x, entry.graph_pin_y = (float(i), float(-i)) if i % 17 == 0 else (None, None)
    entry.discarded_tags = json.dumps(["noise"]) if i % 43 == 0 else "[]"
    entry.updated_at = entry.created_at + timedelta(hours=1)
    return entry


def _attach(session, entry, uploads_dir: Path, name: str, payload: bytes, i: int) -> None:  # noqa: ANN001
    from memorymap.core.database import Attachment

    stored = f"{uuid.UUID(int=entry.id * 1000 + i).hex}{Path(name).suffix}"
    (uploads_dir / stored).write_bytes(payload)
    session.add(Attachment(entry_id=entry.id, filename=name, stored_name=stored, mime="image/png" if name.endswith(".png") else "text/plain",
                           size=len(payload), created_at=entry.created_at, caption=f"caption {entry.id}" if i % 2 else None,
                           ocr_text=f"read {i}" if i % 3 == 0 else None))


def _links_and_reminders(session, entries: list) -> None:  # noqa: ANN001
    from memorymap.core.database import EntryLink, Reminder

    for i, entry in enumerate(entries):
        if i % 3 == 0:
            target = entries[(i + 5) % len(entries)]
            session.add(EntryLink(source_entry_id=entry.id, target_entry_id=target.id, created_at=entry.created_at,
                                  reason=f"both about tide {i}" if i % 2 else None, link_type=["related", "supports", None][i % 3],
                                  origin="user" if i % 2 else "ai", two_way=True if i % 9 == 0 else None,
                                  props={"weight": i % 5} if i % 15 == 0 else None))
        if i % 9 == 0:
            session.add(Reminder(entry_id=entry.id, text=f"check note {i}", due_at=entry.created_at + timedelta(days=1),
                                 done=i % 18 == 0, priority=["low", "normal", "high"][i % 3], recurring="weekly" if i % 27 == 0 else "none",
                                 alert_minutes=15 if i % 2 else None, created_at=entry.created_at,
                                 done_at=entry.created_at + timedelta(days=2) if i % 18 == 0 else None))
        if i % 19 == 0 and i:
            entry.parent_id = entries[i - 1].id


def _documents(session, entries: list) -> None:  # noqa: ANN001
    from memorymap.core.database import Document, DocumentLink, Reminder

    for d in range(5):
        when = BASE + timedelta(days=d)
        document = Document(title=f"Report {d}", content=f"# Report {d}\n\nBody of report {d}.", file_type="md",
                            created_at=when, updated_at=when + timedelta(hours=2),
                            archived_at=when if d == 3 else None)
        session.add(document)
        session.flush()
        session.add(DocumentLink(document_id=document.id, entry_id=entries[d * 10 % len(entries)].id, created_at=when))
        if d == 1:
            session.add(Reminder(document_id=document.id, text="send the report", due_at=when + timedelta(days=4), created_at=when))


def _boards(session, entries: list) -> None:  # noqa: ANN001
    from memorymap.core.database import WhiteboardNode, WhiteboardObject, WhiteboardSketch
    from memorymap.entry import manager

    for b in range(3):
        board = manager.create_entry(session, f"Board {b}", category_name="Work")
        board.is_board = True
        board.board_settings = json.dumps({"grid": b % 2 == 0})
        board.created_at = BASE + timedelta(days=b)
        board.updated_at = board.created_at
        session.flush()
        for n in range(4):
            session.add(WhiteboardNode(board_id=board.id, entry_id=entries[(b * 20 + n) % len(entries)].id, x=10.0 * n, y=5.0 * b, z=n,
                                       locked=n == 1, comments=[{"text": "look"}] if n == 2 else None, created_at=board.created_at,
                                       updated_at=board.created_at))
        session.add(WhiteboardSketch(board_id=board.id, data=json.dumps({"points": [[0, 0], [b, b]]}), created_at=board.created_at,
                                     updated_at=board.created_at))
        frame = WhiteboardObject(board_id=board.id, kind="frame", data="{}", created_at=board.created_at, updated_at=board.created_at)
        session.add(frame)
        session.flush()
        for k in range(2):
            session.add(WhiteboardObject(board_id=board.id, kind="shape", data=json.dumps({"label": f"s{k}"}), parent_id=frame.id,
                                         x=float(k), created_at=board.created_at, updated_at=board.created_at))


def build(session, uploads_dir: Path, count: int = 500) -> dict:  # noqa: ANN001
    """Make the notebook. Returns what it made, for the test's counts."""
    from memorymap.entry import manager

    for name, colour, description in CATEGORIES:
        category = manager.get_or_create_category(session, name)
        category.colour, category.description = colour, description
    entries = [_note(session, i) for i in range(count)]
    session.flush()
    attachments = 0
    for i, entry in enumerate(entries):
        if i % 10 == 0:
            _attach(session, entry, uploads_dir, f"photo-{i}.png", bytes([i % 256]) * (64 + i), 0)
            attachments += 1
        if i % 50 == 0:
            _attach(session, entry, uploads_dir, f"photo-{i}.png", b"second " + str(i).encode(), 1)
            attachments += 1
    _links_and_reminders(session, entries)
    _documents(session, entries)
    _boards(session, entries)
    session.commit()
    return {"notes": count, "attachments": attachments, "boards": 3, "documents": 5}
